version: '3.4'

services:
  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: phonebook.db
  absa.phonebook.api:
    build: ./
    container_name: phonebook.api
  absa.phonebook.webapp:
    build: ABSA.PhoneBook.WebApp/phonebook.react.app/
    container_name: phonebook.webapp
